### ISSUE TITLE
mask is empty

### ISSUE THREAD

**Issue by svabhishek29** [zhixuhao/unet#11]
Hi, Thanks for the repo. Has been helpful in learning about NN.

i was trying to execute the net with LUNA 16 dataset. I loaded in the *.mhd files changes added them to an array to create an array of length 1536 X 512 X 512 X 1 and masks of same length. Passed them to a to net for training after subtracting with mean and dividing by std deviation as float 32 format numpy array. while training it is showing loss of 0.78+ and acc of 0.93+ after 10 epochs

after training while testing i get an out put image of only zeros. not mask is generated. can you please help me with this?

**Comment by neuwangmeng** [comment]
better to look for some other repo
