### ISSUE TITLE
Model Performance using IOU

### ISSUE THREAD

**Issue by deaspo** [zhixuhao/unet#123]
IS there a simple way to evaluate the performance of the model using iou?

**Comment by tamaraalshekhli** [comment]
hi ...i have the same problem i just want to evaluate the prediction ...so have you find a way to do the evaluation ?

**Comment by deaspo** [comment]
> hi ...i have the same problem i just want to evaluate the prediction ...so have you find a way to do the evaluation ?

I used Mean IOU, IOU and Dice coefficient to evaluate my model. Checkout my implementation of the same, specifically modelv2.py and metrics_v2.py at [My Repo](https://github.com/deaspo/Unet_MedicalImagingSegmentation)

**Comment by tamaraalshekhli** [comment]
thank you for your reply ....Ihave couple of questions :
1- I saw in your repo you had used accuracy and IOU,mean _IOU and dice_coef, for training and then for evaluation also , in  my case i used accuracy only in the training, so is it ok to use IOU,mean _IOU and dice_coef in the evaluation similar like you?

2- because I'm completely new to the deep learning area, from  modelv2.py after getting the model what is the next step to get the values of the evaluation is it  model.fit again but this time the comparison will be between the true_label and the prediction ?, I'm sorry for this foolish question but can you explain for me please 

thank you for your help

**Comment by deaspo** [comment]
> thank you for your reply ....Ihave couple of questions :
> 1- I saw in your repo you had used accuracy and IOU,mean _IOU and dice_coef, for training and then for evaluation also , in my case i used accuracy only in the training, so is it ok to use IOU,mean _IOU and dice_coef in the evaluation similar like you?
> 
> 2- because I'm completely new to the deep learning area, from modelv2.py after getting the model what is the next step to get the values of the evaluation , I'm sorry for this foolish question but can you explain for me please
> 
> thank you for your help

Question 1. The metric when using binary_crossentropy is accuracy, see [kears metric](https://keras.io/metrics/), you can substitute this with the others listed above.
Question 2.  The values are the returned  from output of model.fit or model.fit_generator, see [Keras models](https://keras.io/models/model/). From this output or history object you can get the results i.e. history = mode.ft(..) or history = model.fit_generator(...)

Happy to answer any other question

**Comment by tamaraalshekhli** [comment]
thank you so much you've saved me I've been struggling with this matter for a while now ,I was confused with model.evalute and model.evalute_generator but none of those worked for me

**Comment by tamaraalshekhli** [comment]
I got this error TypeError: flow_from_directory() got multiple values for argument 'target_size'
I used my own data which is colored images (224x224x3) in training the model 
and my predictions is gray scale slimier to the true_label , is this the cause of this error ? because Im using pretrained model to  do the evaluation, 
how to solve this error please

**Comment by deaspo** [comment]
> I got this error TypeError: flow_from_directory() got multiple values for argument 'target_size'
> I used my own data which is colored images (224x224x3) in training the model
> and my predictions is gray scale slimier to the true_label , is this the cause of this error ? because Im using pretrained model to do the evaluation,
> how to solve this error please

The error you are receiving is because of difference between input and target sizes. If you check the data.py, there is target_size variable and in model.py there is input_size. Make sure they are marching/same. In addition, this pretrained model was trained on data of input_size? error is because input_size for the model differs from the target_size used in the creation of prediction. These two have to be the same

**Comment by tamaraalshekhli** [comment]
I know you are right this is what i did Ive changed the input size to 224x224x1 to mach the target size which is a gray scale as a color mode  what did i missed ?

**Comment by deaspo** [comment]
> I know you are right this is what i did Ive changed the input size to 224x224x1 to mach the target size which is a gray scale as a color mode also , but this is weird even after i changed the input size to 1 channel in the model.summary the input images still colored 224x224x3, what did i missed ?
 Am not sure if it is because you're using a model pretrained on 224x224x3 or you haven't refreshed and restarted the kernel after making the changes in python files.

Getting the same error still?

**Comment by tamaraalshekhli** [comment]
yes I checked everything I don't know what did i missed and I refreshed the kernel several times, in case the cause is the pretraind model that i used was on 224x224x3 , how to fix this and make it compatible for grayscale image?

**Comment by deaspo** [comment]
> yes I checked everything I don't know what did i missed and I refreshed the kernel several times, in case the cause is the pretraind model that i used was on 224x224x3 , how to fix this and make it compatible for grayscale image?

I think you can try to find how u-net was modified for rgb, see [discussion here](https://github.com/zhixuhao/unet/issues/59) or just search u-net rgb and follow the links

**Comment by tamaraalshekhli** [comment]
thank you so much for your help

**Comment by tamaraalshekhli** [comment]
hi again .... I have more questions if you have time I hope you can answer it please,
1- as the evaluation processes is like a transfer learning and retrain the model with new data , do we need to do data augmentation also,more data better result or should do the evaluation on the original predictions only ?
2- i got confused with evaluate.model and evaluate.model_generator is it working only for classification tasks ? and for the confusion matrix can we plot it for the segmentation task or not ?
3- for the segmentation task is this the only way to do the evaluation for the predictions or there are more approaches?
4- is it ok to evalute the prediction without using the weighs of the original model (the  pretrained one)it would be the same cnn design though ?

really sorry for my to many questions but as i mentioned before I'm a newbie in deep learning and the available sources are not that clear especially for beginners, thank you again for your help

**Comment by deaspo** [comment]
> hi again .... I have more questions if you have time I hope you can answer it please,
> 1- as the evaluation processes is like a transfer learning and retrain the model with new data , do we need to do data augmentation also,more data better result or should do the evaluation on the original predictions only ?
> 2- i got confused with evaluate.model and evaluate.model_generator is it working only for classification tasks ? and for the confusion matrix can we plot it for the segmentation task or not ?
> 3- for the segmentation task is this the only way to do the evaluation for the predictions or there are more approaches?
> 4- is it ok to evalute the prediction without using the weighs of the original model (the pretrained one)it would be the same cnn design though ?
> 
> really sorry for my to many questions but as i mentioned before I'm a newbie in deep learning and the available sources are not that clear especially for beginners, thank you again for your help

Q1 . Evaluation is just checking how the currently trained model performs to 'new' data. You can use the results to fine tune the model training. This is when the metrics score come to play. You can do data augmentation if you don't have enough data for validation. You 1st split the data into train, validation and test set. Ideally you can mix the train and validation set but at any one time they consist of different datasets. If you prefer you can use F-Folds cross validation to have the best mix of the three splits.

Q2. Not only for classification tasks The one with _generator is when you are using a data generator to feed data to your model. We can plot for the segmentation task also

Q3. There are more approaches, IOU, Dice and Mean IOU are populars ones. Searching for evaluation of DL models will lead you to others.

You read the following [tutorial](https://www.pyimagesearch.com/2018/12/24/how-to-use-keras-fit-and-fit_generator-a-hands-on-tutorial/).

And if you are using the U-Net model, in the original paper you or online you can find evaluations that are applicable to it or even evaluations for Segmentations related task. [kaggle](https://www.kaggle.com/pestipeti/explanation-of-scoring-metric) is a good place to start with.

**Comment by tamaraalshekhli** [comment]
thank you so much for your continuous help..... 
i did the evaluation like you said but i got a very weird result the IOU is about 40% and mean IOU is about 0.07 or something I also used f1_score all of these metrics start to drop for each epoch even its reached to minus and my prediction from the model was really good almost similar to the true label and the training accuracy was about 97% and the validation was about 96% and the prediction as i mentioned was so good ,
but in the evaluation i don't know why this happened , any advised please , thank you again

**Comment by deaspo** [comment]
Try not measuring all the metrics at the same time. Measuring Dice and iou at the same time has that effect also. I'll advise one at a time

**Comment by tamaraalshekhli** [comment]
thank you so much i will try that

**Comment by tamaraalshekhli** [comment]
Ive tried to measure the metrics individually but its gave me the same unrealistic result , the prediction Id got from training the model  was  good so I'm not sure where is my mistake exactly 

 
![227](https://user-images.githubusercontent.com/40663330/60165837-007a0580-983b-11e9-9565-fe59e94227a9.png)
true_label
![227_predict](https://user-images.githubusercontent.com/40663330/60165903-1daed400-983b-11e9-934a-2b1e18868749.jpg)
prediction

as far as i know the accuracy that should be reported in the scientific papers its the one from the evaluation , am I right? so i don't know if there is a way around to get the evaluation for the model , any idea how to do that ? thank you really for your help all that time

**Comment by tamaraalshekhli** [comment]
I'm sorry for my too many questions....but because the predictions that I got its in somehow are good so i think maybe my mistake is in the evaluation process... i just used the same pipeline that Ive used in the training process the only thing that Ive  changed is the data that become(true_label and the predictions) and the metrics that you've mentioned before do I need to change something else?  thank you in advance

**Comment by tamaraalshekhli** [comment]
Hi ... after I trained the network without the augmentation the first issue that I encountered  for decreasing the matrices values has disappeared and all the matrices starts to increasing but very slowly the the problem is the train has stopped on the 13th epochs with is error 
InvalidArgumentError: assertion failed: [`labels` out of bound] [Condition x < y did not hold element-wise:] [x (metrics_5/mean_iou/mean_iou_9/confusion_matrix/control_dependency:0) = ] [0 0 0...] [y (metrics_5/mean_iou/mean_iou_9/ToInt64_2:0) = ] [2]
	 [[Node: metrics_5/mean_iou/mean_iou_9/confusion_matrix/assert_less/Assert/AssertGuard/Assert = Assert[T=[DT_STRING, DT_STRING, DT_STRING, DT_INT64, DT_STRING, DT_INT64], summarize=3, _device="/job:localhost/replica:0/task:0/device:CPU:0"](metrics_5/mean_iou/mean_iou_9/confusion_matrix/assert_less/Assert/AssertGuard/Assert/Switch/_7625, metrics_5/mean_iou/mean_iou_9/confusion_matrix/assert_less/Assert/AssertGuard/Assert/data_0, metrics_5/mean_iou/mean_iou_9/confusion_matrix/assert_less/Assert/AssertGuard/Assert/data_1, metrics_5/mean_iou/mean_iou_9/confusion_matrix/assert_less/Assert/AssertGuard/Assert/data_2, metrics_5/mean_iou/mean_iou_9/confusion_matrix/assert_less/Assert/AssertGuard/Assert/Switch_1/_7627, metrics_5/mean_iou/mean_iou_9/confusion_matrix/assert_less/Assert/AssertGuard/Assert/data_4, metrics_5/mean_iou/mean_iou_9/confusion_matrix/assert_less/Assert/AssertGuard/Assert/Switch_2/_7629)]]

I think its related to the classes but i dont know how to solve it

**Comment by deaspo** [comment]
> Ive tried to measure the metrics individually but its gave me the same unrealistic result , the prediction Id got from training the model was good so I'm not sure where is my mistake exactly
> 
> ![227](https://user-images.githubusercontent.com/40663330/60165837-007a0580-983b-11e9-9565-fe59e94227a9.png)
> true_label
> ![227_predict](https://user-images.githubusercontent.com/40663330/60165903-1daed400-983b-11e9-934a-2b1e18868749.jpg)
> prediction
> 
> as far as i know the accuracy that should be reported in the scientific papers its the one from the evaluation , am I right? so i don't know if there is a way around to get the evaluation for the model , any idea how to do that ? thank you really for your help all that time

It is true, the one reported are from the evaluation metrics. Am curious if this is because you are using a pre-trained model for predictions. If you do not mind, can you share the notebook you're running the code from?

**Comment by tamaraalshekhli** [comment]
hi sure i will share it but still i need to do the evaluation in order to know the real accuracy on my work coz im doing a research relating to my thesis so i need  everything be done before sharing anything    ..
but for clarification ,first  i didn't use unet  i used a res-unet  i design it and second thing i didn't use the pretrained model due the error that i encountered the first model i trained it end to end  my point was according to the prediction which is considered good so the evaluation suppose to be good also and i surprised  because the IOU result was about 48% for the 13th epoch before i got the error that i posted previously i don't know if the IOU will increase after the fix the error

**Comment by deaspo** [comment]
> hi sure i will share it but still i need to do the evaluation in order to know the real accuracy on my work coz im doing a research relating to my thesis so i need everything be done before sharing anything ..
> but for clarification ,first i didn't use unet i used a res-unet i design it and second thing i didn't use the pretrained model due the error that i encountered the first model i trained it end to end my point was according to the prediction which is considered good so the evaluation suppose to be good also and i surprised because the IOU result was about 48% for the 13th epoch before i got the error that i posted previously i don't know if the IOU will increase after the fix the error

Please have a look at the following [notebook implementation](https://bitbucket.org/deaspo/unet_medicalimagingsegmentation/src/master/trainUnet_wBody_mod.ipynb?viewer=nbviewer).

We can discuss from there

**Comment by tamaraalshekhli** [comment]
thank you its really useful I can see your metrics started to increase gradually i hope i will get the same result after fix the error that Ive got

**Comment by deaspo** [comment]
> thank you its really useful I can see your metrics started to increase gradually i hope i will get the same result after fix the error that Ive got

How are you addressing overfitting problem? (metrics tend to give lower/plateaued scores if that problem exists..)

**Comment by tamaraalshekhli** [comment]
I'm not sure if i understand your question correctly( as i mentioned before I'm very newbie in deep learning stuffs )but the metrics starts very low and Mean_Iou start with 43%  then all the matrices started to increase but with a very slow pace till i got the error on the 13th epoch 
I'm wondering how is your prediction your scores are very good

**Comment by deaspo** [comment]
> I'm not sure if i understand your question correctly( as i mentioned before I'm very newbie in deep learning stuffs )but the metrics starts very low and Mean_Iou start with 43% then all the matrices started to increase but with a very slow pace till i got the error on the 13th epoch
> I'm wondering how is your prediction your scores are very good

I used the metrics to get the idea of how my trained model will perform on unseen data (Generalize to new data) and also to fine tune the hyperparameters (continuous data preparation also). Because I had feeling that am having overfitting problem after inspecting the evaluation results. Other reason was to compare my results to other deep learning architectures solving the same kind of problem and the original u-net. (wasn't really using/looking at the taining accuracy and loss values, focus was on val_accuray, val_loss, val_iou, val_meaniou, val_dice)

So in case you are wondering why my predictions looks better is because I was focusing on the above objectives to train my model until I got satisfactory results (wasn't one on one run but several with incremental improvements to hyperparameters and data preparation): not only visually but also better metric scores

> Hi ... after I trained the network without the augmentation the first issue that I encountered for decreasing the matrices values has disappeared and all the matrices starts to increasing but very slowly the the problem is the train has stopped on the 13th epochs with is error
> InvalidArgumentError: assertion failed: [`labels` out of bound] [Condition x < y did not hold element-wise:] [x (metrics_5/mean_iou/mean_iou_9/confusion_matrix/control_dependency:0) = ] [0 0 0...] [y (metrics_5/mean_iou/mean_iou_9/ToInt64_2:0) = ] [2]
> [[Node: metrics_5/mean_iou/mean_iou_9/confusion_matrix/assert_less/Assert/AssertGuard/Assert = Assert[T=[DT_STRING, DT_STRING, DT_STRING, DT_INT64, DT_STRING, DT_INT64], summarize=3, _device="/job:localhost/replica:0/task:0/device:CPU:0"](metrics_5/mean_iou/mean_iou_9/confusion_matrix/assert_less/Assert/AssertGuard/Assert/Switch/_7625, metrics_5/mean_iou/mean_iou_9/confusion_matrix/assert_less/Assert/AssertGuard/Assert/data_0, metrics_5/mean_iou/mean_iou_9/confusion_matrix/assert_less/Assert/AssertGuard/Assert/data_1, metrics_5/mean_iou/mean_iou_9/confusion_matrix/assert_less/Assert/AssertGuard/Assert/data_2, metrics_5/mean_iou/mean_iou_9/confusion_matrix/assert_less/Assert/AssertGuard/Assert/Switch_1/_7627, metrics_5/mean_iou/mean_iou_9/confusion_matrix/assert_less/Assert/AssertGuard/Assert/data_4, metrics_5/mean_iou/mean_iou_9/confusion_matrix/assert_less/Assert/AssertGuard/Assert/Switch_2/_7629)]]
> 
> I think its related to the classes but i dont know how to solve it

This is an issue with res-net(), check from the [forums](https://www.google.com/search?q=InvalidArgumentError%3A%20assertion%20failed%3A%20[labels%20out%20of%20bound]%20[Condition%20x%20<%20y%20did%20not%20hold%20element-wise%3A) and how they solved it

**Comment by tamaraalshekhli** [comment]
you are right but if you have a good prediction which is the goal of deep learning model (getting better prediction on real world data) that's mean your model is working right?coz the metrics alone sometimes be deceiving like over fitting  problem .... for me i think i had over fitting situation when i used my first data there were no much diversity to make the model learn better (I'm using aerial images to extract roads) when i changed the data i got a better results and what makes my results more better is when i used cropping its helps me a lot ... in my case  even though the majority of my prediction data is very good (1584 sample the whole data set) and its represent for me now as benchmark to compare it with metrics as i told you first time the metrics was unrealistic comparing with the results of prediction...so in your case the predicted image was very good comparing with the results of metrics that you've got ?
thank you for the link i will check it and i hope that i can fix the error ....can you explain please when exactly we can use evaluate_generator comparing with the evaluation process what the difference ? and one more question  when you said you felt that you have an overfilling  was it because you had high accuracy and not good prediction or some of the prediction was not good enough or you depend on something else to know that you have an overfilling ?
thank you really for your help

**Comment by deaspo** [comment]
> you are right but if you have a good prediction which is the goal of deep learning model (getting better prediction on real world data) that's mean your model is working right?coz the metrics alone sometimes be deceiving like over fitting problem .... for me i think i had over fitting situation when i used my first data there were no much diversity to make the model learn better (I'm using aerial images to extract roads) when i changed the data i got a better results and what makes my results more better is when i used cropping its helps me a lot ... in my case even though the majority of my prediction data is very good (1584 sample the whole data set) and its represent for me now as benchmark to compare it with metrics as i told you first time the metrics was unrealistic comparing with the results of prediction...so in your case the predicted image was very good comparing with the results of metrics that you've got ?
> thank you for the link i will check it and i hope that i can fix the error ....can you explain please when exactly we can use evaluate_generator comparing with the evaluation process what the difference ? and one more question when you said you felt that you have an overfilling was it because you had high accuracy and not good prediction or some of the prediction was not good enough or you depend on something else to know that you have an overfilling ?
> thank you really for your help

You right, my model is working right and there is still room for improvement in %. But this is just the tip of the iceberg, as you say; addressing the overfiiting problem. I took number of steps to counter the same: relyinng on the metric values wasn't enough. The nbook I shared is just one of the final models.

I started addressing the overfitting problem right from prep of segmentation maps, learning rate, u-net architecture modification of the layers and others (as shown in the notebook). At 1st was having the same issues as you, so I played around with hyper-parameters. I've never trusted the accuracy and loss values...prolly because am dealing with medical CT-A images and from experience a qualified physicians perspective is needed. So I added the metrics and re-did the splitting and shuffling datasets until results started improving. Even had suspicion that my validation set was not well balanced so I kept on reshuffling and mixing. 


Anyway there is a lot I could say...also the metrics calc. can be an issue. For me Mean IOU was the most informative..

**Comment by deaspo** [comment]
The following parameters have a significant impact on the metrics, accuracy ,loss:

- batch_size
- steps_per_epoch_val  --> **(num samples used for validation)/batch_size**
- steps_per_epoch_train --> **(num samples used for training)/batch_size**
- learning rate --> **ReduceLROnPlateau** or **CyclicLearningRate** or **modify it and check performance**
-- num of epochs

Try modifying the above as shown in bold and see how the performance

**Comment by tamaraalshekhli** [comment]
thank you so much i will try to modify the parameters that you'd mentioned previously

**Comment by tamaraalshekhli** [comment]
Hi ...Ive tried your advice and I retrain the model with (mean_iou, and dice_coef)in addition to the accuracy, but the predicted images from the model that had trained with accuracy only  was way better that the predicted images from other metrics,and according to a lot of researches that should avoid the accuracy as metric ,I got confused according to this the prediction from these metrics should be clearer than the accuracy, I didn't evaluate the model yet but in this case should i take the prediction of the accuracy and do the evaluation on the other metrics ? 





![871](https://user-images.githubusercontent.com/40663330/60576091-b30c1400-9db7-11e9-805d-fe9660a7771f.jpg)
      true_label



![871_predict](https://user-images.githubusercontent.com/40663330/60576587-ac31d100-9db8-11e9-9c91-5ea73e0c10fc.jpg)
from accuracy
![871_predict](https://user-images.githubusercontent.com/40663330/60576689-d71c2500-9db8-11e9-8017-4908ca6571a0.jpg)
 from other metrics 
any ideas ?

**Comment by deaspo** [comment]
> didn't evaluate the model yet but in this case should i take the prediction of the accuracy and do the evaluation on the other metrics ?

I normally don't look so much at the accuracy metric,  just shows how well the training performs (depends on the loss function used). Besides it uses default keras metric (I think binary_accuracy ...). If your concern is how the model performs to unseen or generalizes to new data then go with the what the literature review is saying. The metric **simply judge the performance of the model**, if your concern is how the model performs then you should looking at the loss functions used for instance. The metric **simply judges the loss function** and if you want to **evaluate** the model start relying on other metrics like IOU, dice, mean iou etc. developed specifically for that purpose

**Comment by tamaraalshekhli** [comment]
actually I need both (good prediction and good accuracy ) the prediction to do further research and  a good evaluation results of course ...but my concern if there is something wrong because I didn't expect that I will get better prediction from the accuracy

**Comment by deaspo** [comment]
> actually I need both (good prediction and good accuracy ) the prediction to do further research and a good evaluation results of course ...but my concern if there is something wrong because I didn't expect that I will get better prediction from the accuracy

There can be a number of things affecting the results outcome i.e from model not being completely trained, hyper-parameters, epochs etc. You use the acc to evaluate the training stage, and then use other metrics to evaluate the model. What are you monitoring during training? Evaluation? Probably  monitor measure variables to do with val_**metrics**, those measure the evaluation. In short the reason for lower evalution metrics and good training metrics can be explained by [this](https://images.app.goo.gl/hYHxvr9ixvyGvniV9)

**Comment by tamaraalshekhli** [comment]
sorry for  late replay my monitor is loss in training and evaluation ... and Ive trained the model again with IOU, mean _iou , dice coef and Ive  got a good predictions also, the mean_iou was about 91 % but when im trying to evaluate the model with the same metrics its start to decrease for each epoch till I got the same error on the 13th epoch .... I dont know why only in the evaluation Ive got this error while everything works perfect in the training , do I need to do a certain processing for the true label and the prediction before evaluate the model? because the only difference between the training and evaluation is the data

**Comment by deaspo** [comment]
> sorry for late replay my monitor is loss in training and evaluation ... and Ive trained the model again with IOU, mean _iou , dice coef and Ive got a good predictions also, the mean_iou was about 91 % but when im trying to evaluate the model with the same metrics its start to decrease for each epoch till I got the same error on the 13th epoch .... I dont know why only in the evaluation Ive got this error while everything works perfect in the training , do I need to do a certain processing for the true label and the prediction before evaluate the model? because the only difference between the training and evaluation is the data

Please share the code where you train and where you evaluate the model and also the error log

**Comment by tamaraalshekhli** [comment]
Thank you for your reply...can you please send me your email I will send it to you as a python file I don’t use repo. Is it ok?

**Comment by tamaraalshekhli** [comment]
hi ... thank you for your reply ... the problem has been solved after several trails and delete the mean_iou , i will use only the iou and dice_coef , but i have another question related to the finale value for the metrics i saw in your new rep df.describ(), and there are the mean , std, min, max value for each metric which one  will be reported as a finale results is it the max?   
and do you have good implementation for f1_score , precision and recall Id tried several once but didn't works for me 
thank you for your help really appropriate it

**Comment by deaspo** [comment]
> hi ... thank you for your reply ... the problem has been solved after several trails and delete the mean_iou , i will use only the iou and dice_coef , but i have another question related to the finale value for the metrics i saw in your new rep df.describ(), and there are the mean , std, min, max value for each metric which one will be reported as a finale results is it the max?
> and do you have good implementation for f1_score , precision and recall Id tried several once but didn't works for me
> thank you for your help really appropriate it

The final scores that you report are the mean plus or minus the standard deviation of the metrics or alternatively you report the final metric values in the last epoch. But it is better to report the average +- srd deviation.

I don't have good implementation of f1_score, precision, maybe you can share your implementation and we can find a way to improve it.

Glad you able to find what combination of metrics that work for you. Besides from iou, you can still calculate the mean, so you don't need to also measuring the mean_iou at the same time

**Comment by tamaraalshekhli** [comment]
thank you for your help so far... for the final score of the model I found there is a lot of opinions about  this , one of those is choosing the best epochs accuracy within the model , the other said take the average without any addition for std , and there is who take the final epochs accuracy  as final score .... do you have a link or article or anything refer to this matter please ?

**Comment by deaspo** [comment]
Nope, my answer was based on what I consider as a true description of the model and it's behaviour. In my opinion the std deviation is important esp. if I want to know how the model behaves when given new data

**Comment by eadeola** [comment]
Please can you send me the github link to the UNET model code having  TEST, TRAIN & VALIDATION.

Thanks

**Comment by jcarta** [comment]
> IS there a simple way to evaluate the performance of the model using iou?

I use this: https://github.com/martinkersner/py_img_seg_eval/blob/master/eval_segm.py

**Comment by sivaramakrishnan-rajaraman** [comment]
> > hi ...i have the same problem i just want to evaluate the prediction ...so have you find a way to do the evaluation ?
> 
> I used Mean IOU, IOU and Dice coefficient to evaluate my model. Checkout my implementation of the same, specifically modelv2.py and metrics_v2.py at [My Repo](https://github.com/deaspo/Unet_MedicalImagingSegmentation)

Is you mean_iou computing the average precision score for a range of iou thresholds between 0.5 and 1.0 in the interval of 0.05? Because the IoU metric is already calculating the iou for each class and computing the average over all the classes. I think the mean_iou term is confusing. Could you please suggest in this regard? Thanks in advance
