### ISSUE TITLE
error when checking target

### ISSUE THREAD

**Issue by shardul2903** [zhixuhao/unet#140]
i) in your model.py
   input_size (256,256,1) => (256,256,3)
ii) trainGenerator function in your data.py
    image_color_mode ="grayscale"=>"rgb"
iii) testGenerator function in your data.py    
    comment out "img = np.reshape(img,img.shape+(1,)) if (not flag_multi_class) else img"

_Originally posted by @teamo429 in https://github.com/zhixuhao/unet/issues/59#issuecomment-439797032_

I followed the above steps but I get the following error:
ValueError: Error when checking target: expected conv2d_24 to have shape (256, 256, 1) but got array with shape (256, 256, 3)

**Comment by reachsak** [comment]
have you resolve this problem , I'm having the exact same problems , hope your solution help

**Comment by sudhasubramaniam** [comment]
In data.py we have in testGenerator
 img = np.reshape(img,img.shape+(1,)) if (not flag_multi_class) else img
you have change it to 
 img = np.reshape(img,img.shape+(3,)) if (not flag_multi_class) else img
This will solve the issue

**Comment by shardul2903** [comment]
@sudhasubramaniam thanks

**Comment by manvirvirk** [comment]
i have made above changes as images but i git following error:
ValueError: Error when checking target: expected conv2d_11 to have shape (16, 16, 1) but got array with shape (256, 256, 1)
Can you please solve it. Thanks @shardul2903  @sudhasubramaniam
