### ISSUE TITLE
ImportError: No module named 'libtiff'

### ISSUE THREAD

**Issue by ranjiewwen** [zhixuhao/unet#16]
- now i'm use python3.5 
- but i can't find libtiff for py3;only for py2?
- anyone else meet this problem? please help me ,thanks!

**Comment by orpheus92** [comment]
What happened after you install libtiff with pip3 install libtiff --user?

**Comment by zhixuhao** [comment]
不用安装这个库了，我将原始tif图分开了,见data文件夹

**Comment by prativadas** [comment]
when I import "from libtiff import TIFF" then i am getting this error on kaggle kernel
ModuleNotFoundError: No module named 'libtiff'

can anyone please help

**Comment by caozd999** [comment]
conda-installed libtff, but when trying `from libtiff import TIFF` in jupyter notebook, I got the following error:
`ModuleNotFoundError: No module named 'libtiff'`, could anybody help please?

**Comment by alexCranfield** [comment]
I had this issue as well. Uninstalling then re-ininstalling with pip seemed to fix it.

First, I tried `conda uninstall libtiff`, which ended up creating a new issue involving the 'brotli' module. I fixed that using [this thread](https://github.com/conda/conda/issues/9903).  

After that, I reinstalled using `pip install libtiff', and this now seems to be working.

**Comment by ndhverma** [comment]
Try with the command 

pip install libtiff

I hope this will help you
