### ISSUE TITLE
Where can I find the test file? Why can't I find it?

### ISSUE THREAD

**Issue by happy20200** [zhixuhao/unet#191]

**Comment by n12ikip12ain** [comment]
unet/data/membrane/

**Comment by n12ikip12ain** [comment]
should be there

**Comment by happy20200** [comment]
Thanks for the reply, er, I see the test data, but I wanted to say I'm trying to find where I can test the code to test my own images @n12ikip12ain

**Comment by n12ikip12ain** [comment]
I just tried to change the images in the folder. The issue is the gray sqaure that is produced. I never got it to work I ended up using a different one, which worked better, but I dont remember which

**Comment by happy20200** [comment]
@n12ikip12ain Ohhh, I see, I'm only getting the full grey image now too... you mean you switched networks or something?

**Comment by n12ikip12ain** [comment]
no i just found another  unet code that seemed to work better.

**Comment by n12ikip12ain** [comment]
https://github.com/iamkrut/image_inpainting_resnet_unet
I used the unet of this one successfully

**Comment by happy20200** [comment]
@n12ikip12ain Thank you very much. I'll check it out.

**Comment by happy20200** [comment]
@n12ikip12ain Image inpainting using RESNET，tha is ,i want to do a crack test.
