### ISSUE TITLE
run unet.py failed

### ISSUE THREAD

**Issue by zhcf** [zhixuhao/unet#5]
I downloaded the repository and tried running unet.py, then I met the err
IOError: [Errno 2] No such file or directory: '../npydata/imgs_train.npy'

**Comment by zhixuhao** [comment]
you can download the data from http://pan.baidu.com/s/1qY3ARA8 ,password:2sy3

**Comment by samiche92** [comment]
Hello i can't download it, is it just for me or any one else has this problem ?
