### ISSUE TITLE
multi labeled data

### ISSUE THREAD

**Issue by VincentChen2016** [zhixuhao/unet#6]
Hi,
This model is suitable for binary segmentation. What if I want to do multi-label segmentation?

Best,

**Comment by zhixuhao** [comment]
you should generate image label mask with shape (n,512,512,m), n is the number of images and m is number of classes. and image is 512*512. you can refer to my responsitory. https://github.com/zhixuhao/unet-multi

**Comment by zhixuhao** [comment]
here is the data https://github.com/preddy5/segnet/tree/master/CamVid

**Comment by MainakBhattacharya** [comment]
Hi @zhixuhao , so basically instead of learning 1 mask for an input image, the model should learn m different masks corresponding to m classes?
