### ISSUE TITLE
merge TypeError

### ISSUE THREAD

**Issue by ianbenlolo** [zhixuhao/unet#62]
Every time i try simply creating the model and getting the model summary (the exact same model as in data.py) i get `TypeError: 'module' object is not callable`. Any clue why this is? Also, what is concat_axis and why is it 3? I can't seem to find the merge function anywhere in the api.. 

Thanks

**Comment by ajithvallabai** [comment]
@ianbenlolo  you can go through this issue https://github.com/zhixuhao/unet/issues/46
