### ISSUE TITLE
为什么我在python2.7环境下，测试图片都是灰的，同样的代码在其他人机器上就能测试成功

### ISSUE THREAD

**Issue by FENGShuanglang** [zhixuhao/unet#67]
![image](https://user-images.githubusercontent.com/38462831/44898826-9be13d80-ad32-11e8-960e-eba969838979.png)

**Comment by leetesua** [comment]
same

**Comment by jjj90** [comment]
same here!

**Comment by jjj90** [comment]
Assuming that the image you posted is the result of your prediction. Could you please translate your question to English? :)

**Comment by lifangda01** [comment]
Solution is proposed in #65

**Comment by openXG** [comment]
> Solution is proposed in #65

thanks,bro.

**Comment by PanPan0210** [comment]
i have the same problem

**Comment by chegnyanjun** [comment]
As far as I can see, I think the possible reason is that the format of the image is somewhat different from the format of the image in the project, so the training has no effect, and the final test has no effect. I also encountered this problem, I trained with my own liver data, but my image has a bit depth of 24, which is equivalent to the format of my image is RGB, and the depth of the image in the project is 8, so training will not give an error, but the training is not effective. So you need to convert your own image format to 8. I just use opencv to convert the image to grayscale, and then the bit depth of the image is 8, and last the test will have an effect.

**Comment by FengZhiheng** [comment]
I have the same problem. Sad

**Comment by chegnyanjun** [comment]
很抱歉现在才回复你啦，一直没看到，抱歉。你可以看一下是不是图片的问题，当时我们的情况是这样的，我们使用了开源的代码unet，但数据集是自己制作的。可能的原因是图片存在位深的差别，我记得当时一个图像的位深位8，就是灰度图的格式，另一个图像的位深位24，就是彩色图的格式，所以你的图像与公开训练集上的图像看起来都是灰色的，其实位深不一样，也即是图像的格式不一样。所以就可能存在两种问题，你训练的网络完全没有学习到，测试自然就没效果，就是灰的；二就是网络学到了，测试图片存在问题，即格式有问题，也就是我说的图像位深的问题，需要调整图像格式。当然，这只是我碰到的问题，可能还有其他的原因，仅供参考啦。祝大佬一切顺利。


------------------ 原始邮件 ------------------
发件人: "GodFish"<notifications@github.com>;
发送时间: 2019年7月23日(星期二) 晚上8:56
收件人: "zhixuhao/unet"<unet@noreply.github.com>;
抄送: "cyj"<2735123258@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [zhixuhao/unet] 为什么我在python2.7环境下，测试图片都是灰的，同样的代码在其他人机器上就能测试成功 (#67)




I have the same problem. Sad

**Comment by FengZhiheng** [comment]
> I have the same problem. Sad

我的问题解决了，我发现我使用错了loss function；默认的是binary_crossentropy，我把他换成了dice_loss，dice_loss的定义如下：
——————————
I have resolved my proble by changing default loss(binary_crossentropy) to dice_loss；
the defination of my dice loss is below:
——————————
`
def dice_coef(y_true,y_pred,epsilon=1e-8):
    axes = tuple(range(1,len(y_pred.shape)-1))
    intersection = 2.*K.sum(y_true*y_pred,axes)
    return (intersection + epsilon)/(K.sum((K.square(y_true)+K.square(y_pred)),axes) + epsilon)

def dice_coef_loss(y_ture,y_pred):
    return 1-dice_coef(y_ture,y_pred)
`

**Comment by seazp** [comment]
> binary_crossentropy

could you tell me how to change lose function, ts

**Comment by chegnyanjun** [comment]
非常抱歉现在才回复你拉，最近有点忙，对不起啦。这是一个朋友跟我讨论时，他说的解决方法，你可以参考一下啦。

I have the same problem. Sad

我的问题解决了，我发现我使用错了loss function；默认的是binary_corssentropy，我把他换成了dice_loss，dice_loss的定义如下：
——————————
I have resolve my proble by changing default loss(binary_corssentropy) to dice_loss；
the defination of my dice loss is below:
——————————
`def dice_coef(y_true,y_pred,epsilon=1e-8):
axes = tuple(range(1,len(y_pred.shape)-1))
intersection = 2.K.sum(y_truey_pred,axes)
return (intersection + epsilon)/(K.sum((K.square(y_true)+K.square(y_pred)),axes) + epsilon)

def dice_coef_loss(y_ture,y_pred):
return 1-dice_coef(y_ture,y_pred) `

—





------------------ 原始邮件 ------------------
发件人: "seazp"<notifications@github.com>;
发送时间: 2019年7月28日(星期天) 晚上10:36
收件人: "zhixuhao/unet"<unet@noreply.github.com>;
抄送: "cyj"<2735123258@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [zhixuhao/unet] 为什么我在python2.7环境下，测试图片都是灰的，同样的代码在其他人机器上就能测试成功 (#67)



 
binary_crossentropy
  
could you tell me how to change lose function, ts
